# Torch

> Torch


- skip_showdoc: true
- skip_exec: true

In [ ]:
#| default_exp torch

In [ ]:
import torch
import numpy as np

In [ ]:
torch.cuda.is_available()

True

## Creation Operations

### torch.is_tensor

In [ ]:
x = torch.tensor([1, 2, 3])
x, torch.is_tensor(x)

(tensor([1, 2, 3]), True)

### torch.set_default_device

In [ ]:
torch.tensor([1.2, 3]).device

device(type='cpu')

In [ ]:
torch.set_default_device('cuda')  # current device is 0
torch.tensor([1.2, 3]).device

device(type='cuda', index=0)

In [ ]:
torch.set_default_device('cpu')
a = torch.arange(1000000)
a

tensor([     0,      1,      2,  ..., 999997, 999998, 999999])

In [ ]:
%%time 
a + 1

CPU times: user 13 ms, sys: 8.74 ms, total: 21.8 ms
Wall time: 3.59 ms


tensor([      1,       2,       3,  ...,  999998,  999999, 1000000])

In [ ]:
torch.set_default_device('cuda')
a = torch.arange(1000000)
a

tensor([     0,      1,      2,  ..., 999997, 999998, 999999], device='cuda:0')

In [ ]:
%%time 
a + 1

CPU times: user 4.25 ms, sys: 0 ns, total: 4.25 ms
Wall time: 686 µs


tensor([      1,       2,       3,  ...,  999998,  999999, 1000000],
       device='cuda:0')

### torch.get_default_dtype

In [ ]:
torch.get_default_dtype()  # initial default for floating point is torch.float32

torch.float32

In [ ]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()  # default is now changed to torch.float64

torch.float64

### torch.set_printoptions

In [ ]:
# Limit the precision of elements
torch.set_printoptions(precision=2)
torch.tensor([1.12345])

tensor([1.12], device='cuda:0')

In [ ]:
# Limit the number of elements shown
torch.set_printoptions(threshold=5)
torch.arange(10)

tensor([0, 1, 2,  ..., 7, 8, 9], device='cuda:0')

In [ ]:
# Restore defaults
torch.set_printoptions(profile='default')
torch.tensor([1.12345])

tensor([1.1235], device='cuda:0')

In [ ]:
torch.set_default_device('cpu')
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### torch.as_tensor

In [ ]:
a = np.array([1, 2, 3])
t = torch.as_tensor(a)
t

tensor([1, 2, 3])

In [ ]:
t[0] = -1
a

array([-1,  2,  3])

In [ ]:
a = np.array([1, 2, 3])
t = torch.as_tensor(a, device=torch.device('cuda'))
t

tensor([1, 2, 3], device='cuda:0')

In [ ]:
t[0] = -1
a

array([1, 2, 3])

In [ ]:
t

tensor([-1,  2,  3], device='cuda:0')

### torch.zeros

In [ ]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [ ]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

### torch.range

In [ ]:
torch.arange(5), torch.arange(1, 4), torch.arange(1, 2.5, 0.5)

(tensor([0, 1, 2, 3, 4]), tensor([1, 2, 3]), tensor([1.0000, 1.5000, 2.0000]))

In [ ]:
torch.linspace(3, 10, steps=5),\
torch.linspace(-10, 10, steps=5),\
torch.linspace(start=-10, end=10, steps=5),\
torch.linspace(start=-10, end=10, steps=1)

(tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000]),
 tensor([-10.,  -5.,   0.,   5.,  10.]),
 tensor([-10.,  -5.,   0.,   5.,  10.]),
 tensor([-10.]))

In [ ]:
torch.logspace(start=-10, end=10, steps=5),\
torch.logspace(start=0.1, end=1.0, steps=5),\
torch.logspace(start=0.1, end=1.0, steps=1),\
torch.logspace(start=2, end=2, steps=1, base=2)

(tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10]),
 tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000]),
 tensor([1.2589]),
 tensor([4.]))

In [ ]:
torch.empty((2,3), dtype=torch.int64)

tensor([[94749913133952, 94749913151920,              0],
        [             0,              0,              1]])

In [ ]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### torch.quantize_per_tensor

In [ ]:
torch.set_default_dtype(torch.float32)

In [ ]:
torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8),\
torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8).int_repr(),\
torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), torch.tensor(0.1), torch.tensor(10), torch.quint8)

(tensor([-1.,  0.,  1.,  2.], size=(4,), dtype=torch.quint8,
        quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10),
 tensor([ 0, 10, 20, 30], dtype=torch.uint8),
 tensor([-1.,  0.,  1.,  2.], size=(4,), dtype=torch.quint8,
        quantization_scheme=torch.per_tensor_affine, scale=0.10000000149011612,
        zero_point=10))

### torch.complex

In [ ]:
real = torch.tensor([1, 2], dtype=torch.float32)
imag = torch.tensor([3, 4], dtype=torch.float32)
z = torch.complex(real, imag)
z.dtype

torch.complex64

In [ ]:
real, imag, z

(tensor([1., 2.]), tensor([3., 4.]), tensor([1.+3.j, 2.+4.j]))

### torch.polar

In [ ]:
import numpy as np
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

## Indexing, Slicing, Joining, Mutating Ops

### torch.cat

In [ ]:
x = torch.randn(2, 3)
x

tensor([[-0.0332, -0.3678, -0.3927],
        [-0.0963, -1.6820, -1.0661]])

In [ ]:
torch.cat((x, x, x), 0)

tensor([[-0.0332, -0.3678, -0.3927],
        [-0.0963, -1.6820, -1.0661],
        [-0.0332, -0.3678, -0.3927],
        [-0.0963, -1.6820, -1.0661],
        [-0.0332, -0.3678, -0.3927],
        [-0.0963, -1.6820, -1.0661]])

In [ ]:
torch.cat((x, x), 1)

tensor([[-0.0332, -0.3678, -0.3927, -0.0332, -0.3678, -0.3927],
        [-0.0963, -1.6820, -1.0661, -0.0963, -1.6820, -1.0661]])

### torch.conj

In [ ]:
x = torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j])
x, x.is_conj()

(tensor([-1.+1.j, -2.+2.j,  3.-3.j]), False)

In [ ]:
y = torch.conj(x)
y, y.is_conj()

(tensor([-1.-1.j, -2.-2.j,  3.+3.j]), True)

### torch.permute

In [ ]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

### torch.reshape

In [ ]:
a = torch.arange(4.)
a

tensor([0., 1., 2., 3.])

In [ ]:
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [ ]:
b = torch.tensor([[0, 1], [2, 3]])
b

tensor([[0, 1],
        [2, 3]])

In [ ]:
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

### torch.movedim

In [ ]:
t = torch.randn(2,3,5)
t.size()

torch.Size([2, 3, 5])

In [ ]:
torch.movedim(t, 1, 0).shape

torch.Size([3, 2, 5])

In [ ]:
torch.movedim(t, 1, 0)

tensor([[[-0.1846,  1.5819,  0.8201,  2.2313,  0.1465],
         [-0.9358,  1.3307, -0.6214, -0.1436,  1.0005]],

        [[-0.8220, -1.3351, -0.1963,  0.0436,  0.7320],
         [-0.9467, -1.6281, -1.0026,  0.1112,  0.7087]],

        [[ 0.8604,  0.1986, -0.3472, -0.2072,  0.2923],
         [ 0.7192,  0.7690, -1.3123, -0.4890, -0.3867]]])

In [ ]:
torch.movedim(t, (1, 2), (0, 1)).shape

torch.Size([3, 5, 2])

### torch.split

In [ ]:
a = torch.arange(10).reshape(5, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
torch.split(a, 2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [ ]:
torch.split(a, [1, 4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

### torch.t

In [ ]:
x = torch.randn(())
x, torch.t(x)

(tensor(-0.9816), tensor(-0.9816))

In [ ]:
x = torch.randn(3)
x, torch.t(x)

(tensor([ 1.0798, -0.0350, -1.4501]), tensor([ 1.0798, -0.0350, -1.4501]))

In [ ]:
x = torch.randn(2, 3)
x, torch.t(x)

(tensor([[ 1.2736,  2.1246, -0.7236],
         [-2.1417,  1.9549,  0.6174]]),
 tensor([[ 1.2736, -2.1417],
         [ 2.1246,  1.9549],
         [-0.7236,  0.6174]]))