# Save and Load

> Save and Load

- skip_showdoc: true
- skip_exec: true

In [ ]:
import torch
import torch.nn as nn

## Save arg dict with python pickle

```python
torch.save(arg, PATH)
torch.load(PATH)
model.load_state_dict(arg)
```

## Save model with python pickle

```python
torch.save(model, PATH)

model = torch.load(PATH)

model.eval()
```

## Recommented Method

```python
torch.save(model.state_dict(), PATH)

model = Model(*args, **kwargs)

model.load_state_dict(torch.load(PATH))

model.eval()
```

## Test model

In [ ]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred



In [ ]:
device = torch.device("cuda")
model = Model(n_input_features = 6)
model

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

## Method 1

In [ ]:
FILE = "model.pth1"
torch.save(model, FILE)

In [ ]:
model = torch.load(FILE)
model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [ ]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.3002, -0.2477, -0.2695, -0.1810, -0.0604,  0.1516]],
       requires_grad=True)
Parameter containing:
tensor([-0.3233], requires_grad=True)


## Method 2

In [ ]:
FILE = "model.pth2"
torch.save(model.state_dict(), FILE)


In [ ]:
model = Model(n_input_features = 6)

In [ ]:
model.load_state_dict(torch.load(FILE))

model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [ ]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.3002, -0.2477, -0.2695, -0.1810, -0.0604,  0.1516]],
       requires_grad=True)
Parameter containing:
tensor([-0.3233], requires_grad=True)


In [ ]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[-0.3002, -0.2477, -0.2695, -0.1810, -0.0604,  0.1516]])),
             ('linear.bias', tensor([-0.3233]))])

In [ ]:
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.01,
   'momentum': 0,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'maximize': False,
   'foreach': None,
   'differentiable': False,
   'params': [0, 1]}]}

In [ ]:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}
checkpoint

{'epoch': 90,
 'model_state': OrderedDict([('linear.weight',
               tensor([[-0.3002, -0.2477, -0.2695, -0.1810, -0.0604,  0.1516]])),
              ('linear.bias', tensor([-0.3233]))]),
 'optim_state': {'state': {},
  'param_groups': [{'lr': 0.01,
    'momentum': 0,
    'dampening': 0,
    'weight_decay': 0,
    'nesterov': False,
    'maximize': False,
    'foreach': None,
    'differentiable': False,
    'params': [0, 1]}]}}

In [ ]:
torch.save(checkpoint, "checkpoint.pth")

In [ ]:
loaded_checkpoint = torch.load("checkpoint.pth")

In [ ]:
loaded_checkpoint['epoch']

90

In [ ]:
model.load_state_dict(loaded_checkpoint['model_state'])
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[-0.3002, -0.2477, -0.2695, -0.1810, -0.0604,  0.1516]])),
             ('linear.bias', tensor([-0.3233]))])

In [ ]:
optimizer.load_state_dict(loaded_checkpoint['optim_state'])
optimizer.state_dict()


{'state': {},
 'param_groups': [{'lr': 0.01,
   'momentum': 0,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'maximize': False,
   'foreach': None,
   'differentiable': False,
   'params': [0, 1]}]}